### PR TITLE
Fix the issue #237

### LINKED ISSUE #237: Consecutive struct initializations confuses dfmt
``` d
struct A
{
    int x, y, z;
}

int main()
{
    int fun()
    {
        import std.stdio : writeln;
        import std.typecons : tuple;
        A a = { tuple(Variant(1))[0].get!int, tuple(Variant(2))[0].get!int, tuple(Variant(3))[0].get!int};
        A b = { tuple(Variant(1))[0].get!int, tuple(Variant(2))[0].get!int, tuple(Variant(3))[0].get!int};
        writeln(a);
    }
}

```

dfmt result:

``` d
struct A
{
    int x, y, z;
}
int main()
{
    int fun()
    {
        import std.stdio : writeln;
        import std.typecons : tuple;
        A a = {
            tuple(Variant(1))[0].get!int, tuple(Variant(2))[0].get!int,
                tuple(Variant(3))[0].get!int};
            A b = {
                tuple(Variant(1))[0].get!int, tuple(Variant(2))[0].get!int,
                    tuple(Variant(3))[0].get!int};
                writeln(a);
            }
        }

```

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
This fixes #237 by remembering whether we indented because of struct-initializers.
and then popping the indent specifically.

### CODE REVIEW

**Comment by stefan-koch-sociomantic** [comment]
this doesn't work to well because of `,`-wrap-Indents.

**Comment by stefan-koch-sociomantic** [comment]
I am aware this does not look great, but making this work properly would mean a*major* re-factoring.

File: src/dfmt/formatter.d [hunk 1]
```diff
@@ -850,7 +850,6 @@ private:
             }
             if (sBraceDepth > 0)
                 sBraceDepth--;
-
```
Comment (leandro-lucarella-sociomantic) [inline src/dfmt/formatter.d]: Change unrelated to the commit, I would leave the line as it is since it doesn't really changes anything and just pollutes the diff.

File: src/dfmt/ast_info.d [hunk 2]
```diff
@@ -8,6 +8,21 @@ module dfmt.ast_info;
 import dparse.lexer;
 import dparse.ast;
 
+enum LocationPairFlags
+{
+    TempIndent = 1 << 0,
+}
+
+struct LocationPair
```
Comment (Hackerpilot) [inline src/dfmt/ast_info.d]: A pair with four things in it?

File: src/dfmt/ast_info.d [hunk 3]
```diff
@@ -85,6 +103,8 @@ struct ASTInformation
 
     /// Locations of constructor/destructor "this" tokens ?
     size_t[] constructorDestructorLocations;
+
+    LocationPair[] sortedByEndLocation;
```
Comment (Hackerpilot) [inline src/dfmt/ast_info.d]: This should probably be called something like `braceIndentInfo` because it contains information about the indentation of open/close brace pairs instead of information about sorting by end locations.

File: src/dfmt/formatter.d [hunk 4]
```diff
@@ -803,15 +813,34 @@ private:
 
     void formatRightBrace()
     {
-        if (astInformation.structInitEndLocations.canFindIndex(tokens[index].index))
+        void popToBeginIndent(LocationPair locPair)
```
Comment (Hackerpilot) [inline src/dfmt/formatter.d]: It looks like this is trying to solve the same problem that `indentToMostRecent` on the indent stack should be solving.

Comment (UplinkCoder) [reply src/dfmt/formatter.d]: oh it was not oblivious from the code of from naming

**Comment by UplinkCoder** [comment]
@Hackerpilot `indentToMostRecent` may not work if a non-struct-literal `{` has been pushed, at least I believe so.

**Comment by stefan-koch-sociomantic** [comment]
@leandro-lucarella-sociomantic this currently blocks other work which needs the `BraceIdentInfo`

File: src/dfmt/ast_info.d [hunk 5]
```diff
@@ -8,6 +8,21 @@ module dfmt.ast_info;
...
+{
+    TempIndent = 1 << 0,
+}
+
+struct BraceIndentInfo
+{
+    size_t startLocation;
+    size_t endLocation;
+
+    uint flags;
```
[the remark this answers is not in the document]
Comment (stefan-koch-sociomantic) [reply src/dfmt/ast_info.d]: because it's not guaranteed to be just one value but could use remaining bits for something else.

File: src/dfmt/formatter.d [hunk 6]
```diff
@@ -803,15 +813,34 @@ private:
...
+            if (indentInfo.flags & BraceIndentInfoFlags.TempIndent)
+            {
+                popToBeginIndent(indentInfo);
+                simpleNewline();
+                indent();
+            }
             writeToken();
         }
-        else if (astInformation.funLitEndLocations.canFindIndex(tokens[index].index))
+        else if (astInformation.funLitEndLocations.canFindIndex(tokens[index].index, &pos))
```
[the remark this answers is not in the document]
Comment (stefan-koch-sociomantic) [reply src/dfmt/formatter.d]: actually all of indices in here _have_ to be unique.
If they are not we really messed up something, I like having the assert.
