### PR TITLE
Fix Issue #469

### LINKED ISSUE #469: Invalid escape sequences truncate output and errorcode = success
example code (should be \ueee8 for valid unicode escape):

import std.stdio; void main() { writeln("\eee8Hello"); int a = 5; }

outputs:

main.d(0:0)[error]: Primary expression expected
main.d(0:0)[error]: Expected `}` instead of `EOF`
import std.stdio;

void main()
{
    writeln(!ERROR!

with error code = 0, which is painful when using Format on save option in IDEs because it can quietly remove huge parts of code.

### PR DESCRIPTION
**Pull request by Hackerpilot**
Check for lexer errors, and exit with a non-zero status if any are found. Fixes #469.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
Forgot about the dub build...

File: tests/test.sh [hunk 1]
```diff
@@ -6,13 +6,22 @@ do
...
 		diff -u "${braceStyle}/${source}.ref" "${braceStyle}/${source}.out"
 	done
 done
+
+set +e
+
+for source in expected_failures/*.d
+do
+	if ../bin/dfmt "${source}" > /dev/null; then
+		exit 1
```
Comment (WebFreak001) [inline tests/test.sh]:
```suggestion
		echo "Expected failure on test ${source} but passed"
		exit 1
```

File: src/dfmt/formatter.d [hunk 2]
```diff
@@ -33,11 +43,18 @@ void format(OutputRange)(string source_desc, ubyte[] buffer, OutputRange output,
     auto visitor = new FormatVisitor(&astInformation);
     visitor.visit(mod);
     astInformation.cleanup();
-    auto tokens = byToken(buffer, config, &cache).array();
+    auto tokenRange = byToken(buffer, config, &cache);
+    auto app = appender!(Token[])();
+    for (; !tokenRange.empty(); tokenRange.popFront())
+        app.put(tokenRange.front());
+    auto tokens = app.data;
```
Comment (WebFreak001) [inline src/dfmt/formatter.d]: why no longer using `array()`?
```d
auto tokenRange = byToken(buffer, config, &cache);
auto tokens = tokenRange.array();
```
should work fine, no?

File: src/dfmt/main.d [hunk 3]
```diff
@@ -211,14 +211,15 @@ else
                 else
                     break;
             }
-            format("stdin", buffer, output.lockingTextWriter(), &config);
+            return format("stdin", buffer, output.lockingTextWriter(), &config);
```
Comment (WebFreak001) [inline src/dfmt/main.d]: pretty sure this will have the opposite effect of what is intended: return `true` = error code 1 (failure), return false = error code 0 (success)

File: src/dfmt/formatter.d (hunk 2 above)
Comment (WebFreak001) [reply src/dfmt/formatter.d]: nvm array would have save'd the struct and not emitted any errors then

File: src/dfmt/main.d (hunk 3 above)
Comment (Hackerpilot) [reply src/dfmt/main.d]: What's really dumb is that I got this right in the other branch of the code...
